### ISSUE TITLE
PYthon code is not Working

### ISSUE THREAD

**Issue by Storma-X** [MyloWhylo/PrinterBot#1]
I can´t run the Code it has this error 
`  File "/home/pi/PrinterBot-main/main.py", line 134
    global blockedChannels
    ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'blockedChannels' is assigned to before global declaration`
Can you pls Fix it ?

**Comment by MyloWhylo** [comment]
I fixed your issue. Please re-clone the repository in order to get the latest version.
